# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    

    runs-on: ubuntu-latest
    env:
      working-directory: ./web

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - name: Create Firebase config
      run: |
        ls
        mkdir web/src/config
        echo $FIREBASE_CONFIG > web/src/config/FirebaseTemplate.js
      shell: bash
      env:
        FIREBASE_CONFIG: ${{secrets.FIREBASE_CONFIG}}
      working-directory: ./web
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run
      working-directory: ./web
    - run: npm install
      working-directory: ./web
    - run: npm run build --if-present
      working-directory: ./web
    - run: npm run test
      working-directory: ./web
